from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from datetime import datetime
import io

class LectureNotesPDFGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.setup_custom_styles()
    
    def setup_custom_styles(self):
        """Setup custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a237e'),
            spaceAfter=30,
            alignment=TA_CENTER
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#3949ab'),
            spaceAfter=12,
            spaceBefore=12
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['BodyText'],
            fontSize=11,
            alignment=TA_JUSTIFY,
            spaceAfter=12
        ))
    
    def generate_pdf(self, notes_data, output_file=None):
        """Generate PDF from lecture notes data"""
        if output_file is None:
            buffer = io.BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=letter)
        else:
            doc = SimpleDocTemplate(output_file, pagesize=letter)
        
        story = []
        
        # Title
        title = Paragraph(notes_data.get('title', 'Lecture Notes'), self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 0.2*inch))
        
        # Metadata table
        metadata = [
            ['Subject:', notes_data.get('subject', 'N/A')],
            ['Faculty:', notes_data.get('faculty', 'N/A')],
            ['Date:', notes_data.get('date', datetime.now().strftime('%Y-%m-%d'))],
            ['Duration:', notes_data.get('duration', 'N/A')],
            ['Word Count:', str(notes_data.get('word_count', 0))]
        ]
        
        metadata_table = Table(metadata, colWidths=[1.5*inch, 4*inch])
        metadata_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f0f0')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
        ]))
        
        story.append(metadata_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Summary section
        if notes_data.get('summary'):
            summary_heading = Paragraph('Summary', self.styles['CustomHeading'])
            story.append(summary_heading)
            
            summary_text = Paragraph(notes_data['summary'], self.styles['CustomBody'])
            story.append(summary_text)
            story.append(Spacer(1, 0.2*inch))
        
        # Key points section
        if notes_data.get('key_points'):
            key_points_heading = Paragraph('Key Points', self.styles['CustomHeading'])
            story.append(key_points_heading)
            
            for i, point in enumerate(notes_data['key_points'], 1):
                point_text = Paragraph(f"{i}. {point}", self.styles['CustomBody'])
                story.append(point_text)
            
            story.append(Spacer(1, 0.3*inch))
        
        # Full transcript section
        if notes_data.get('transcript'):
            transcript_heading = Paragraph('Full Transcript', self.styles['CustomHeading'])
            story.append(transcript_heading)
            
            # Split transcript into paragraphs
            paragraphs = notes_data['transcript'].split('\n')
            for para in paragraphs:
                if para.strip():
                    para_text = Paragraph(para, self.styles['CustomBody'])
                    story.append(para_text)
        
        # Footer
        story.append(Spacer(1, 0.5*inch))
        footer = Paragraph(
            f'<i>Generated by Smart Classroom Management System - {datetime.now().strftime("%Y-%m-%d %H:%M")}</i>',
            self.styles['Normal']
        )
        story.append(footer)
        
        # Build PDF
        doc.build(story)
        
        if output_file is None:
            buffer.seek(0)
            return buffer
        
        return output_file
    
    def generate_pdf_bytes(self, notes_data):
        """Generate PDF and return as bytes"""
        buffer = self.generate_pdf(notes_data)
        return buffer.getvalue()
